# Generated by Django 5.1.6 on 2025-02-12 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MataKuliah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("dosen", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Jadwal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hari", models.CharField(max_length=10)),
                ("jam_mulai", models.TimeField()),
                ("jam_selesai", models.TimeField()),
                ("pj_whatsapp", models.CharField(max_length=15)),
                (
                    "mata_kuliah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jadwal.matakuliah",
                    ),
                ),
            ],
        ),
    ]
