# Generated by Django 5.1.6 on 2025-02-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jadwal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jadwal",
            name="hari",
            field=models.CharField(
                choices=[
                    ("Senin", "Senin"),
                    ("Selasa", "Selasa"),
                    ("Rabu", "Rabu"),
                    ("Kamis", "Kamis"),
                    ("Jumat", "Jumat"),
                    ("Sabtu", "Sabtu"),
                    ("Minggu", "Minggu"),
                ],
                default="Senin",
                max_length=10,
            ),
        ),
    ]
